#!/usr/bin/env python3
"""M0 — data acquisition. Downloads real public datasets to data/raw/ and records
provenance in outputs/logs/provenance.json (MANIFEST.md is regenerated from it).

Sources (all verified reachable 2026-07-10):
  - DepMap Public 24Q4        figshare article 27993248 -> ndownloader.figshare.com
  - GDSC release-8.4 (24Jul22) Sanger FTP
  - TCGA LAML + DLBC          cBioPortal REST API (panel genes only)
  - Beat AML (aml_ohsu_2022)  cBioPortal REST API (panel genes only)

Idempotent: existing files are skipped. Never edits raw files in place (GUARDRAILS §6).
No fabricated URLs — every endpoint here was confirmed to respond before this was written.
"""
from __future__ import annotations
import json, os, sys, subprocess, datetime, hashlib
from pathlib import Path
import requests
import yaml

ROOT = Path(__file__).resolve().parents[2]
CFG = yaml.safe_load((ROOT / "config.yaml").read_text())
RAW = ROOT / CFG["paths"]["data_raw"]
LOGS = ROOT / CFG["paths"]["outputs_logs"]
PROV = LOGS / "provenance.json"
RAW.mkdir(parents=True, exist_ok=True)
LOGS.mkdir(parents=True, exist_ok=True)

TODAY = datetime.date.today().isoformat()
UA = {"User-Agent": "atap-m8-salvage/1.0 (research; public data)"}


def load_prov() -> dict:
    if PROV.exists():
        return json.loads(PROV.read_text())
    return {}


def save_prov(prov: dict) -> None:
    PROV.write_text(json.dumps(prov, indent=2))
    _write_manifest(prov)


def _write_manifest(prov: dict) -> None:
    lines = [
        "# data/raw/MANIFEST.md — provenance for every raw download.",
        "",
        "Auto-generated by src/data/fetch_data.py. Every raw file has a row here.",
        "",
        "| file | dataset | source | release/version | download date | size MB | sha256[:12] | notes |",
        "|------|---------|--------|-----------------|---------------|---------|-------------|-------|",
    ]
    for k in sorted(prov):
        r = prov[k]
        lines.append(
            f"| {r.get('file','')} | {r.get('dataset','')} | {r.get('source','')} | "
            f"{r.get('release','')} | {r.get('download_date','')} | {r.get('size_mb','')} | "
            f"{r.get('sha256','')[:12]} | {r.get('notes','')} |"
        )
    (RAW / "MANIFEST.md").write_text("\n".join(lines) + "\n")


def sha256(path: Path, limit_mb: float = 500) -> str:
    """Hash up to limit_mb of the file (full hash for small files; prefix for huge)."""
    h = hashlib.sha256()
    n = 0
    cap = int(limit_mb * 1e6)
    with open(path, "rb") as fh:
        while chunk := fh.read(1 << 20):
            h.update(chunk)
            n += len(chunk)
            if n >= cap:
                break
    return h.hexdigest()


def download(url: str, dest: Path) -> bool:
    if dest.exists() and dest.stat().st_size > 0:
        print(f"  skip (exists): {dest.name} ({dest.stat().st_size/1e6:.1f} MB)")
        return True
    tmp = dest.with_suffix(dest.suffix + ".part")
    print(f"  downloading: {dest.name}  <- {url}")
    try:
        with requests.get(url, headers=UA, stream=True, timeout=180) as resp:
            resp.raise_for_status()
            total = int(resp.headers.get("Content-Length", 0))
            got = 0
            with open(tmp, "wb") as out:
                for chunk in resp.iter_content(1 << 20):
                    out.write(chunk)
                    got += len(chunk)
                    if total:
                        print(f"\r    {got/1e6:8.1f}/{total/1e6:.1f} MB", end="", flush=True)
        print()
        tmp.rename(dest)
        return True
    except Exception as e:  # noqa: BLE001
        print(f"\n  FAILED {dest.name}: {e}")
        if tmp.exists():
            tmp.unlink()
        return False


def record(prov, key, file, dataset, source, release, notes=""):
    path = RAW / file
    prov[key] = {
        "file": file,
        "dataset": dataset,
        "source": source,
        "release": release,
        "download_date": TODAY,
        "size_mb": round(path.stat().st_size / 1e6, 1) if path.exists() else None,
        "sha256": sha256(path) if path.exists() else "",
        "notes": notes,
    }


# --------------------------------------------------------------------------
def fetch_depmap(prov):
    print("[DepMap 24Q4]")
    for name, fid in CFG["depmap_files"].items():
        url = f"https://ndownloader.figshare.com/files/{fid}"
        if download(url, RAW / name):
            record(prov, f"depmap::{name}", name, "DepMap",
                    "figshare article 27993248", CFG["data_releases"]["depmap"])
            save_prov(prov)


def fetch_gdsc(prov):
    print("[GDSC 8.4]")
    base = CFG["gdsc_base"]
    for name in CFG["gdsc_files"]:
        if download(f"{base}/{name}", RAW / name):
            record(prov, f"gdsc::{name}", name, "GDSC",
                    "Sanger FTP release-8.4", CFG["data_releases"]["gdsc"])
            save_prov(prov)


# --------------------------------------------------------------------------
def _cbio_post(path, body):
    r = requests.post(f"{CFG['cbioportal_api']}{path}",
                      json=body, headers={**UA, "Accept": "application/json"}, timeout=120)
    r.raise_for_status()
    return r.json()


def _cbio_get(path):
    r = requests.get(f"{CFG['cbioportal_api']}{path}",
                     headers={**UA, "Accept": "application/json"}, timeout=120)
    r.raise_for_status()
    return r.json()


def fetch_cbio_study(prov, label, study_id, dataset_name):
    """Fetch panel-gene expression, mutations, CNA, and clinical for one cBioPortal study."""
    print(f"[cBioPortal {label} = {study_id}]")
    import pandas as pd
    entrez = list(CFG["entrez_ids"].values())
    sym_by_entrez = {v: k for k, v in CFG["entrez_ids"].items()}
    sample_list = f"{study_id}_all"
    out_prefix = RAW / f"cbio_{label}"

    # profiles available in this study
    profiles = {p["molecularAlterationType"]: p["molecularProfileId"]
                for p in _cbio_get(f"/studies/{study_id}/molecular-profiles")}
    # pick preferred profile IDs
    prof_ids = _cbio_get(f"/studies/{study_id}/molecular-profiles")
    pid = {p["molecularProfileId"]: p for p in prof_ids}

    def first(*subs):
        for mid in pid:
            if all(s in mid for s in subs):
                return mid
        return None

    jobs = {
        "expression": first("rna_seq_v2_mrna") or first("rna_seq_mrna") or first("mrna"),
        "cna": first("gistic") or first("log2CNA"),
    }
    for kind, mid in jobs.items():
        if not mid:
            print(f"  no {kind} profile in {study_id}")
            continue
        data = _cbio_post(f"/molecular-profiles/{mid}/molecular-data/fetch",
                          {"sampleListId": sample_list, "entrezGeneIds": entrez})
        if not data:
            print(f"  {kind}: empty")
            continue
        df = pd.DataFrame(data)
        df["gene"] = df["entrezGeneId"].map(sym_by_entrez)
        wide = df.pivot_table(index="sampleId", columns="gene", values="value")
        f = f"cbio_{label}_{kind}.csv"
        wide.to_csv(RAW / f)
        record(prov, f"cbio::{label}::{kind}", f, dataset_name,
               f"cBioPortal API {mid}", study_id,
               notes=f"{wide.shape[0]} samples x {wide.shape[1]} panel genes")
        print(f"  {kind}: {wide.shape[0]} samples x {wide.shape[1]} genes -> {f}")
        save_prov(prov)

    # mutations (panel genes)
    mut_mid = first("mutations")
    if mut_mid:
        muts = _cbio_post(f"/molecular-profiles/{mut_mid}/mutations/fetch",
                          {"sampleListId": sample_list, "entrezGeneIds": entrez})
        if muts:
            mdf = pd.DataFrame(muts)
            keep = [c for c in ["sampleId", "hugoGeneSymbol", "entrezGeneId", "mutationType",
                                "proteinChange", "variantType", "startPosition"] if c in mdf.columns]
            f = f"cbio_{label}_mutations.csv"
            mdf[keep].to_csv(RAW / f, index=False)
            record(prov, f"cbio::{label}::mutations", f, dataset_name,
                   f"cBioPortal API {mut_mid}", study_id,
                   notes=f"{mdf.shape[0]} panel-gene mutation calls")
            print(f"  mutations: {mdf.shape[0]} calls -> {f}")
            save_prov(prov)

    # clinical (all attrs, patient+sample)
    try:
        clin = _cbio_get(f"/studies/{study_id}/clinical-data?clinicalDataType=SAMPLE&projection=SUMMARY")
        cdf = pd.DataFrame(clin)
        if not cdf.empty:
            wide = cdf.pivot_table(index="sampleId", columns="clinicalAttributeId",
                                   values="value", aggfunc="first")
            f = f"cbio_{label}_clinical.csv"
            wide.to_csv(RAW / f)
            record(prov, f"cbio::{label}::clinical", f, dataset_name,
                   "cBioPortal API clinical-data", study_id,
                   notes=f"{wide.shape[0]} samples x {wide.shape[1]} attrs")
            print(f"  clinical: {wide.shape} -> {f}")
            save_prov(prov)
    except Exception as e:  # noqa: BLE001
        print(f"  clinical fetch failed: {e}")


def fetch_beataml2(prov):
    """Beat AML 2.0 native files (inhibitor AUC + RNA-seq + clinical, shared dbgap IDs)."""
    print("[Beat AML 2.0 native (biodev/beataml2.0_data)]")
    base = CFG["beataml2_base"]
    for name in CFG["beataml2_files"]:
        if download(f"{base}/{name}", RAW / name):
            record(prov, f"beataml2::{name}", name, "Beat AML 2.0 (Bottomly 2022)",
                   "biodev/beataml2.0_data GitHub (main)",
                   "Beat AML waves 1-4",
                   notes="ex vivo inhibitor AUC / RNA-seq / clinical" )
            save_prov(prov)


def lock_env():
    try:
        out = subprocess.check_output([sys.executable, "-m", "pip", "freeze"], text=True)
        (LOGS / "environment_lock.txt").write_text(out)
        print(f"[env] locked {len(out.splitlines())} packages -> environment_lock.txt")
    except Exception as e:  # noqa: BLE001
        print(f"[env] freeze failed: {e}")


def main():
    which = sys.argv[1:] or ["depmap", "gdsc", "tcga", "beataml", "beataml2", "env"]
    prov = load_prov()
    if "env" in which:
        lock_env()
    if "depmap" in which:
        fetch_depmap(prov)
    if "gdsc" in which:
        fetch_gdsc(prov)
    if "tcga" in which:
        fetch_cbio_study(prov, "LAML", CFG["tcga_studies"]["LAML"], "TCGA-LAML")
        fetch_cbio_study(prov, "DLBC", CFG["tcga_studies"]["DLBC"], "TCGA-DLBC")
    if "beataml" in which:
        fetch_cbio_study(prov, "BeatAML", CFG["beataml_study"], "Beat AML (OHSU 2022)")
    if "beataml2" in which:
        fetch_beataml2(prov)
    save_prov(prov)
    print("\nMANIFEST written:", RAW / "MANIFEST.md")


if __name__ == "__main__":
    main()
